{
    "type": "bundle",
    "id": "bundle--4225e6eb-2241-474b-a6a9-959544860201",
    "spec_version": "2.0",
    "objects": [
        {
            "type": "relationship",
            "id": "relationship--d7ea83fa-87c7-4d36-96d5-aee554504040",
            "created": "2017-05-31T21:33:27.074Z",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "revoked": false,
            "external_references": [
                {
                    "source_name": "ESET Bad Rabbit",
                    "description": "M.L\u00e9veille, M-E.. (2017, October 24). Bad Rabbit: Not\u2011Petya is back with improved ransomware. Retrieved January 28, 2021.",
                    "url": "https://www.welivesecurity.com/2017/10/24/bad-rabbit-not-petya-back/"
                }
            ],
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "modified": "2025-04-16T23:04:57.606Z",
            "description": "Several transportation organizations in Ukraine have suffered from being infected by [Bad Rabbit](https://attack.mitre.org/software/S0606), resulting in some computers becoming encrypted, according to media reports. (Citation: ESET Bad Rabbit)",
            "relationship_type": "uses",
            "source_ref": "malware--2eaa5319-5e1e-4dd7-bbc4-566fced3964a",
            "target_ref": "attack-pattern--63b6942d-8359-4506-bfb3-cf87aa8120ee",
            "x_mitre_modified_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "x_mitre_deprecated": false,
            "x_mitre_attack_spec_version": "3.2.0"
        }
    ]
}