{
    "type": "bundle",
    "id": "bundle--7be31006-738d-4689-8326-d32c0260220f",
    "spec_version": "2.0",
    "objects": [
        {
            "type": "relationship",
            "id": "relationship--ed7ce0cf-8044-4af8-8acf-db94abb79766",
            "created": "2025-03-22T15:31:08.710Z",
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "revoked": false,
            "external_references": [
                {
                    "source_name": "Cybereason LumaStealer Undated",
                    "description": "Cybereaon Security Services Team. (n.d.). Your Data Is Under New Lummanagement: The Rise of LummaStealer. Retrieved March 22, 2025.",
                    "url": "https://www.cybereason.com/blog/threat-analysis-rise-of-lummastealer"
                }
            ],
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "modified": "2025-04-16T22:55:59.915Z",
            "description": "[Lumma Stealer](https://attack.mitre.org/software/S1213) has used malicious Python scripts to execute payloads.(Citation: Cybereason LumaStealer Undated)",
            "relationship_type": "uses",
            "source_ref": "malware--674c514f-e485-47a8-9d49-1aaa70de155b",
            "target_ref": "attack-pattern--cc3502b5-30cc-4473-ad48-42d51a6ef6d1",
            "x_mitre_modified_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "x_mitre_deprecated": false,
            "x_mitre_attack_spec_version": "3.2.0"
        }
    ]
}